"""empty message

Revision ID: bf34d09de8a9
Revises: 
Create Date: 2019-11-15 05:35:49.736425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf34d09de8a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=100000), nullable=False),
    sa.Column('query_results', sa.String(length=100000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('time_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=64), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=64), nullable=False),
    sa.Column('pword_hash', sa.String(length=128), nullable=False),
    sa.Column('two_fa', sa.String(length=11), nullable=True),
    sa.Column('admin_role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_uname'), 'user', ['uname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uname'), table_name='user')
    op.drop_table('user')
    op.drop_table('time_log')
    op.drop_table('spell')
    # ### end Alembic commands ###
